In [1]:
import pandas as pd

In [10]:
df = pd.read_excel("./data/DART_공정공시골라내기_뉴스크롤링.xlsx", sheet_name='Sheet1')
df.to_csv("./data/dart_data.csv", index=False)

In [14]:
dart_df = pd.read_csv("./data/dart_data.csv")
dart_df

,id,year,date,weekday,time,timezone,company,구분,배당,영업잠정실적,실적전망,장래사업계획
0,1,2021,2021-01-29,금,11:47:00,장중,영풍정밀,배당,1,0,0,0
1,2,2020,2020-12-14,월,11:27:00,장중,나우IB,배당,1,0,0,0
2,3,2020,2020-12-08,화,10:41:00,장중,동구바이오제약,배당,1,0,0,0
3,4,2020,2020-12-02,수,09:38:00,장중,디지털대성,배당,1,0,0,0
4,5,2020,2020-12-29,화,11:46:00,장중,메디아나,배당,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
7088,7089,2018,2018-06-11,월,11:32:00,장중,한프,장래사업계획,0,0,0,1
7089,7090,2018,2018-04-27,금,13:31:00,장중,현대글로비스,장래사업계획,0,0,0,1
7090,7091,2018,2018-04-26,목,15:55:00,장종료,현대모비스,장래사업계획,0,0,0,1
7091,7092,2018,2018-11-01,목,08:48:00,개장전,현대위아,장래사업계획,0,0,0,1
7092,7093,2018,2018-12-19,수,10:41:00,장중,형지엘리트,장래사업계획,0,0,0,1

In [15]:
dart_df = dart_df[dart_df['구분']!='실적전망']

In [16]:
dart_df

,id,year,date,weekday,time,timezone,company,구분,배당,영업잠정실적,실적전망,장래사업계획
0,1,2021,2021-01-29,금,11:47:00,장중,영풍정밀,배당,1,0,0,0
1,2,2020,2020-12-14,월,11:27:00,장중,나우IB,배당,1,0,0,0
2,3,2020,2020-12-08,화,10:41:00,장중,동구바이오제약,배당,1,0,0,0
3,4,2020,2020-12-02,수,09:38:00,장중,디지털대성,배당,1,0,0,0
4,5,2020,2020-12-29,화,11:46:00,장중,메디아나,배당,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
7088,7089,2018,2018-06-11,월,11:32:00,장중,한프,장래사업계획,0,0,0,1
7089,7090,2018,2018-04-27,금,13:31:00,장중,현대글로비스,장래사업계획,0,0,0,1
7090,7091,2018,2018-04-26,목,15:55:00,장종료,현대모비스,장래사업계획,0,0,0,1
7091,7092,2018,2018-11-01,목,08:48:00,개장전,현대위아,장래사업계획,0,0,0,1
7092,7093,2018,2018-12-19,수,10:41:00,장중,형지엘리트,장래사업계획,0,0,0,1

In [32]:
# 날짜 2 / 기업명 6 / 구분 7
dart_class_dict = {"배당":"배당", "장래사업계획":"장래 사업 경영 계획", "영업잠정실적":"영업 잠정 실적"}
for i in range(len(dart_df)):
    search_keyword = f"{dart_df.iloc[i, 6]} {dart_class_dict[dart_df.iloc[i, 7]]}"

In [28]:
search_keyword

'형지엘리트 장래 사업 경영 계획'

In [35]:
tmp = dart_df[dart_df['구분']=='배당']

In [40]:
tmp

,id,year,date,weekday,time,timezone,company,구분,배당,영업잠정실적,실적전망,장래사업계획
0,1,2021,2021-01-29,금,11:47:00,장중,영풍정밀,배당,1,0,0,0
1,2,2020,2020-12-14,월,11:27:00,장중,나우IB,배당,1,0,0,0
2,3,2020,2020-12-08,화,10:41:00,장중,동구바이오제약,배당,1,0,0,0
3,4,2020,2020-12-02,수,09:38:00,장중,디지털대성,배당,1,0,0,0
4,5,2020,2020-12-29,화,11:46:00,장중,메디아나,배당,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
62,63,2018,2018-12-12,수,10:59:00,장중,제룡전기,배당,1,0,0,0
63,64,2018,2018-12-20,목,13:26:00,장중,청담러닝,배당,1,0,0,0
64,65,2018,2018-01-23,화,13:52:00,장중,컬러레이,배당,1,0,0,0
65,66,2018,2018-12-18,화,14:33:00,장중,컴투스,배당,1,0,0,0
66,67,2018,2018-12-10,월,13:38:00,장중,테크윙,배당,1,0,0,0

In [43]:
dart_df.loc[dart_df['company']==name.replace('+', ' ')&dart_df['date']==, 'id']

0          1
1078    1079
1079    1080
2569    2570
2570    2571
2571    2572
2572    2573
4379    4380
4380    4381
4381    4382
4382    4383
6225    6226
6226    6227
6227    6228
Name: id, dtype: int64

In [55]:
df = pd.read_csv("./data/dart_url.csv")

names = list(set(df['name']))
for name in names:
#     id_df.drop(id_df.loc[id_df['name'] == name].index, axis=0, inplace=True)
    tmp = df[df['name']==name]
    num = str(len(tmp)).rjust(8, '0')
    tmp.to_csv(f"./data/dart_url/{num}_{name}.csv", index=False, encoding='utf-8-sig')